apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  ports:
    - port: 28017
      nodePort: 30001
      protocol: TCP
  selector:
    type: backend
    service: go-demo-2
