# For version v1.24 if we still want to create secrets match with service-account with non-expiring token
# Make sure service-account dashboard-sa created first
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: my-secret
  annotations:
    kubernetes.io/service-account.name: dashboard-sa
