apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  securityContext: # set as pod level
    runAsUser: 1000
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "3600"
      securityContext: # set as container level. NOTE: it will override pod level config
        runAsUser: 1000
        capabilities:
          add: ["MAC_ADMIN"]
