apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: demo
  template:
    metadata:
      labels:
        type: backend
        service: demo
        db: mongo
        language: go
    spec:
      containers:
        - name: db
          image: mongo:3.3
        - name: api
          image: vfarcic/go-demo-
          env:
            - name: DB
              value: localhost
          livenessProbe:
            httpGet:
              path: /demo/hello 
              port: 8080
