AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  saml-demo

  Sample SAM Template for saml-demo

Resources:
  StockTradingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/stock_trader.asl.json
      DefinitionSubstitutions:
        StockCheckerFunctionArn: !GetAtt StockCheckerFunction.Arn
        StockSellerFunctionArn: !GetAtt StockSellerFunction.Arn
        StockBuyerFunctionArn: !GetAtt StockBuyerFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref TransactionTable
      Events:
        HourlyTradingSchedule:
          Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
          Properties:
            Description: Schedule to run the stock trading state machine every hour
            Enabled: false # This schedule is disabled by default to avoid incurring charges.
            Schedule: rate(1 hour)
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref StockCheckerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockSellerFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref StockBuyerFunction
        - DynamoDBWritePolicy:
            TableName: !Ref TransactionTable

  TransformZoomRecordingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/transform_zoom_recording.asl.json
      DefinitionSubstitutions:
        TransformRecordingFunctionArn: !GetAtt TransformRecordingFunction.Arn
        UploadTransformedDataFunctionArn: !GetAtt UploadTransformedDataFunction.Arn
        UpdateStateOnPortalFunctionArn: !GetAtt UpdateStateOnPortalFunction.Arn
        RemoveOriginalFormatFunctionArn: !GetAtt RemoveOriginalFormatFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref TransformRecordingFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UploadTransformedDataFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref UpdateStateOnPortalFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RemoveOriginalFormatFunction

  StockCheckerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      CodeUri: functions/stock_checker/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64
  StockSellerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_seller/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64
  StockBuyerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/stock_buyer/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64
  TransactionTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  TransformRecordingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom/transform_recording/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64

  UploadTransformedDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom/upload_transformed_data/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64

  UpdateStateOnPortalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom/update_state_on_portal/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64

  RemoveOriginalFormatFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/zoom/remove_original_format/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64
Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  StockTradingStateMachineArn:
    Description: Stock Trading state machine ARN
    Value: !Ref StockTradingStateMachine
  StockTradingStateMachineRole:
    Description: IAM Role created for Stock Trading state machine based on the specified SAM Policy Templates
    Value: !GetAtt StockTradingStateMachineRole.Arn
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
