apiVersion: v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-volume
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h
  podManagementPolicy: Parallel
  volumeClaimTemplates:
    - metadata:
        name: data-volumne
      spec:
        storageClassName: google-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
